---
- name: playbook to install tomcat
  hosts: webservers
  become: true
  tasks: 
  - name: install java
    yum: 
      name: java
      state: installed

  - name: download tomcat packages
    get_url: 
      url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz
      dest: /opt/

  - name: unarchive tomcat packages
    unarchive:
      src: /opt/apache-tomcat-8.5.50.tar.gz
      dest: /opt/
      remote_src: yes

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.50/bin
